### ISSUE TITLE
How to identify device 

### ISSUE THREAD

**Issue by tuxflo** [jonathanyip/Surface-Pro-3-AutoHotkey#1]
Hey! 
I want to adapt your nice script to my device, a Lenovo Yoga 260. I have the vendor ID and the values from the ahkhid example but don't know how insert them here. 

Thanks for helping, 
Flo

**Comment by jonathanyip** [comment]
Hi! This script was meant to be used with the pen/digitizer included with the Surface Pro 3. Most likely, your Yoga uses a different technology and/or method of encoding pen states, so it's probably not compatible with this script (or it might take a bit more poking around with the ahkhid program). Sorry about that.

**Comment by tuxflo** [comment]
Just in case some other Yoga users read this it works for this device although the state identifiers are different : the state "PEN_TOUCHING" in Line 32 is used for the second Pen button on the device. Useful if one want to remap the default behavior of that button.

**Comment by jonathanyip** [comment]
That's pretty cool! Thanks for sharing. :)
