### ISSUE TITLE
Surface pro 7

### ISSUE THREAD

**Issue by Halpode** [jonathanyip/Surface-Pro-3-AutoHotkey#2]
Hi jonathan yip,

I bought me the new Surface Pro 7 and I tried to use ur script but without any luck. 

Do you have any Idea how I can get it to work?

Greetz
Hamza

**Comment by jonathanyip** [comment]
Hi @Halpode , unfortunately, I don't own my surface pro 3 anymore, and don't own a surface pro 7 to test on, so I would not be able to help you with this :(
I think most likely the surface pro 7 pen/device emits different data from the HID device, and that is why it is not working. To get it working, you'd have to figure out the new format of the data emitted.

If you would like to play around with the source code, I would recommend checking out the AHKHID repository (https://github.com/jleb/AHKHID) and take a look at example_2.ahk, as that shows the raw input coming in from an HID device.
