### ISSUE TITLE
How can i get the position of surface pen cursor  from inputData ?

### ISSUE THREAD

**Issue by Andrwyw** [jonathanyip/Surface-Pro-3-AutoHotkey#3]
I read the source code about getting input data.But I don't know the strcut of the inputData. 

    if (type = RIM_TYPEHID) {
        inputInfo := AHKHID_GetInputInfo(lParam, II_DEVHANDLE)
        inputData := AHKHID_GetInputData(lParam, uData)
        raw := NumGet(uData, 0, "UInt")
        proc := (raw >> 8) & 0x1F

**Comment by jonathanyip** [comment]
Hi @Andrwyw , I don't have a surface pro 3 to test anything on anymore. However, I would recommend checking out the AHKHID repository (https://github.com/jleb/AHKHID) and take a look at example_2.ahk, as that shows the raw input coming in from an HID device. This may contain the position of the pen cursor, which you can extract out and use.
